name: HYIP BTC Scammers
favicon: null
layout_spectrum: 0.23736
typography_spectrum: 0.38393019000068307
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#02194d'
    - '#0070fb'
    - '#024fb6'
    - '#02a2fa'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
