name: HYIP BTC Scammers
favicon: null
layout_spectrum: 0.24985
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#02194d'
    - '#0070fb'
    - '#024fb6'
    - '#02a2fa'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
